// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://riitjmfevukezgcqgsyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpaXRqbWZldnVrZXpnY3Fnc3ljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1ODcwMTMsImV4cCI6MjA2NTE2MzAxM30.1Y24obdx8_P4U1LK8U1Y_uPDdt16hVdH4xU6ek80vhA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);